name: morfo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^9.0.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  syncfusion_flutter_sliders: ^26.1.40
  intl: ^0.19.0

  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo_cod.png
    - assets/images/bca_logo.png
    - assets/images/bri_logo.png
    - assets/images/logo-apps.png
    - assets/images/mandiri_logo.png
